### ISSUE TITLE
zoomgrab dies due to failed regex search

### ISSUE THREAD

**Issue by scoward-r7** [MooseDojo/zoomgrab#4]
the following traceback shows the specific error:

```
Traceback (most recent call last):
  File "zoomgrab.py", line 429, in <module>
    main()
  File "[redacted]/.pyenv/versions/sandbox-env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "[redacted]/.pyenv/versions/sandbox-env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "[redacted]/.pyenv/versions/sandbox-env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[redacted]/.pyenv/versions/sandbox-env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "zoomgrab.py", line 425, in main
    scraper.scrape(store_pagecount=True)
  File "zoomgrab.py", line 114, in scrape
    self._get_pagecount(self.current_page)
  File "zoomgrab.py", line 149, in _get_pagecount
    zoom_total_contacts = zoom_total_contacts_pattern.search(total_search_pages.text.replace(',','')).group('num_contacts')
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by scoward-r7** [comment]
in this scenario, the target company had fewer than 25 results, and the regular expression:
``` python
zoom_total_contacts_pattern = re.compile(r'of (?P<num_contacts>\d+) Contacts')
```
failed to match due to the 'of ' part of the pattern. the regex pattern:
``` python
zoom_total_contacts_pattern = re.compile(r'(?P<num_contacts>\d+) Contacts')
```
will match regardless of result size.
